<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bagheera_docking</name>
  <version>0.1.0</version>
  <description>Nav2 opennav_docking plugin for Bagheera's AprilTag charging dock.</description>
  <maintainer email="Pauli1Go@users.noreply.github.com">Paul Praschl</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>angles</depend>
  <depend>geometry_msgs</depend>
  <depend>mowgli_interfaces</depend>
  <depend>nav2_util</depend>
  <depend>opennav_docking_core</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <exec_depend>opennav_docking</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
